# MCUboot bootloader configuration

# No LFXO on this board
CONFIG_CLOCK_CONTROL_NRF_K32SRC_RC=y
CONFIG_CLOCK_CONTROL_NRF_K32SRC_RC_CALIBRATION=y

# Serial recovery over USB CDC ACM
CONFIG_MCUBOOT_SERIAL=y
CONFIG_BOOT_SERIAL_CDC_ACM=y
CONFIG_USB_DEVICE_MANUFACTURER="VoLoRa"
CONFIG_USB_DEVICE_PRODUCT="DFU"
CONFIG_CONSOLE=n
CONFIG_UART_CONSOLE=n

# Enter serial recovery when button0 (P1.13) is held during boot
CONFIG_BOOT_SERIAL_ENTRANCE_GPIO=y

# LTO to fit in default 64KB boot partition
CONFIG_ISR_TABLES_LOCAL_DECLARATION=y
CONFIG_LTO=y
