# Console over USB CDC ACM
CONFIG_USB_DEVICE_STACK_NEXT=y
CONFIG_CDC_ACM_SERIAL_INITIALIZE_AT_BOOT=y
CONFIG_CDC_ACM_SERIAL_MANUFACTURER_STRING="VoLoRa"
CONFIG_CDC_ACM_SERIAL_PRODUCT_STRING="Serial Port"

# Logging disabled for PDM data capture test
CONFIG_LOG=n

# MCUboot support
CONFIG_BOOTLOADER_MCUBOOT=y
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_IMG_MANAGER=y
CONFIG_STREAM_FLASH=y

# nPM1300 PMIC
CONFIG_I2C=y
CONFIG_MFD=y
CONFIG_MFD_NPM13XX=y
CONFIG_REGULATOR=y
CONFIG_REGULATOR_NPM13XX=y
CONFIG_SENSOR=y
CONFIG_NPM13XX_CHARGER=y
CONFIG_LED=y
CONFIG_LED_NPM13XX=y

# SPI + LoRa
CONFIG_SPI=y
CONFIG_LORA=y

# CMSIS-DSP (used by Codec2 FDV_ARM_MATH path)
CONFIG_CMSIS_DSP=y
CONFIG_CMSIS_DSP_TRANSFORM=y
CONFIG_CMSIS_DSP_BASICMATH=y

# Audio: PDM microphone + I2S speaker
CONFIG_AUDIO=y
CONFIG_AUDIO_DMIC=y
CONFIG_I2S=y
CONFIG_BASE64=y
